name: Issue Autobuild Workflow

on:
  issues:
    types:
      - opened

jobs:
  autobuild:
    runs-on: ubuntu-latest
    if: github.event.issue.labels | contains:'docker-autobuild'
    steps:
      - name: Check if issue has the "docker-autobuild" label
        id: check-label
        run: |
          if jq 'any(.[]; .name == "docker-autobuild")' <<< '${{ toJson(github.event.issue.labels) }}'; then
            has_label="true"
          else
            has_label="false"
          fi
          echo "has_label=$has_label" >> $GITHUB_ENV
      - name: Checkout code
        if: env.has_label == 'true'
        uses: actions/checkout@v2
