name: Issue Autobuild Workflow

on:
  issues:
    types:
      - opened

jobs:
  autobuild:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue has the "docker-autobuild" label
        id: check-label
        run: |
          if jq '. | length == 0' <<< '${{ toJson(github.event.issue.labels) }}'; then
            has_label="false"
          else
            if jq '.[].name | contains ("docker-autobuild")' <<< '${{ toJson(github.event.issue.labels) }}'; then
              has_label="true"
            else
              has_label="false"
            fi
          fi
          echo "has_label=$has_label" >> $GITHUB_ENV
          echo $has_label
      - name: Checkout code
        if: env.has_label == 'true'
        uses: actions/checkout@v2
